import "@/assets/reset.scss";
import "@/assets/style.scss";
import "@/app/globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";

import { Providers } from "./components/Providers";
export const metadata = {
    title: "Mindmap Flow",
    // description: "Generated by create next app",
    icons: "./favicon.ico",
    description:
        "Powerful & Easy To Use — Your Ideas Deserve A Beautiful Online Mind Map Canvas. Start For Free. Upgrade Anytime. ",
    metadataBase: process.env.NEXT_PUBLIC_HOST,
    openGraph: {
        description:
            "Powerful & Easy To Use — Your Ideas Deserve A Beautiful Online Mind Map Canvas. Start For Free. Upgrade Anytime. ",
        images: [
            "https://upload.wikimedia.org/wikipedia/commons/c/cf/Elements_of_the_culture_mindmap.png",
        ],
    },
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Providers>
                    <main>
                        <UserProvider>{children}</UserProvider>
                    </main>
                </Providers>
            </body>
        </html>
    );
}
