import "@/assets/reset.scss";
import "@/assets/style.scss";
import "@/app/globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";

import { Providers } from "./components/Providers";
export const metadata = {
    title: "Mindmap Flow",
    description: "Generated by create next app",
    icons: "./favicon.ico",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Providers>
                    <main>
                        <UserProvider>{children}</UserProvider>
                    </main>
                </Providers>
            </body>
        </html>
    );
}
